export const FILTER_LETTER = 'FILTER_LETTER';
export const REQUEST_CONTACTS = 'REQUEST_CONTACTS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const SEARCH_QUERY = 'SEARCH_QUERY';
export const SET_CONNECTIONS = 'SET_CONNECTIONS';
export const UPDATE_CONTACTS = 'UPDATE_CONTACTS';
export const UPDATE_SELECTED_CONTACT = 'UPDATE_SELECTED_CONTACT';
